### ISSUE TITLE
Review before submit

### ISSUE THREAD

**Issue by iaurg** [vcwild/webserv#17]
This is just a reminder and checklist for us to review before evaluation:

- [x] our Makefile must at least contain the rules: **$(NAME)**, **all**, **clean**, **fclean** and **re**
- [x] Compile your code with c++ and the flags -Wall -Wextra -Werror
- [x] Try to always develop using the most C++ features you can (for example, choose **<cstring>** over **<string.h>**).
- [x] Any external library and Boost libraries are forbidden
- [x] You have to turn in a Makefile which will compile your source files. It must not relink
- [x] You can’t execve another web server
- [x] You must never do a read or a write operation without going through poll() (or equivalent).
- [x] Checking the value of errno is strictly **forbidden** after a read or a write operation.
- [x] Check if server is working on Google Chrome
- [x] The important thing is resilience. Your server should never die.
- [x] Rules review

**Comment by vcwild** [comment]
Done!
