### ISSUE TITLE
Close socket based on timeout on config

### ISSUE THREAD

**Issue by vcwild** [vcwild/webserv#22]
The timeout of closing sockets must be equal to the one set in the config file. Use the `Config` struct to get this information.

**Comment by vcwild** [comment]
There is no timeout config set on the config file. I was mistaken. Blocking this one for now.

**Comment by iaurg** [comment]
Partially solved close connections here:
https://github.com/vcwild/webserv/pull/20/files#diff-e10827bcb577143c11889834d2172c0e9f31a5a01ab83af388416f5d20c61720R5-R9
