### ISSUE TITLE
Handle methods and response

### ISSUE THREAD

**Issue by iaurg** [vcwild/webserv#32]
- [x]  Validate GET file types (image, txt, gif, html...)
- [x] Handle POST request (the easy way, not over engineering)
- [x] Validate Content-Type of POST
- [x] Check if can write into server
- [x] Create a new file based on request
- [x] Handle DELETE method
- [x] Check if can DELETE requested resource
- [x] Validate body size based on config

**Comment by iaurg** [comment]
Os valores de location não possuem uma separação, o config está guardando sempre o último valor lido, com isso não conseguimos separar ações e configurações para cada nivel de location, por exemplo:
/teste - não mostrar a listagem de diretorio
/autoindex - mostra a listagem

Como separar e considerar qual utilizar? A informação do primeiro é perdida

**Comment by vcwild** [comment]
Dá pra corrigir isso criando um vec de locations para armazenar todos os locations.
![image](https://user-images.githubusercontent.com/49621396/222932946-39239de7-9262-40b0-a547-daa4c2ded86d.png)

**Comment by iaurg** [comment]
- [ ] try multiple server with hostname
- [ ] validate limit body size
- [ ] implement redirect
- [ ] validate multiports

**Comment by iaurg** [comment]
- [ ] validate different index for locations
- [ ] server can't handle multiple request on different ports (open and navigate into both ports at same time)
- [ ] location not handling allowed methods
- [ ] Upload file to server

**Comment by iaurg** [comment]
If I change the conf `error_page 404 ./conf-4x04.html;` the returns segmentation fault

**Comment by vcwild** [comment]
@iaurg I couldn't reproduce your bug, is it happening on `main`?

**Comment by vcwild** [comment]
@iaurg I tried reproducing it in `fix/allowed-methods` branch and I had no failures at all.
