### ISSUE TITLE
Create the Server (non-blocking HTTP server that uses a single poll function (or equivalent) for all I/O operations and that doesn't use multiple processes and threads)

### ISSUE THREAD

**Issue by MatheusCervieri** [vcwild/webserv#4]
From what I understand we can divide the project into 4 parts:

1- Parse the configuration file.
2- Create the server.
3- Deal with the client request.
4- Send a response to the client based on the request and the configuration file.

When i read the pdf i understand that the server needs to be non-blocking HTTP server that uses a single poll function (or equivalent) for all I/O operations and that doesn't use multiple processes and threads.

Here's an overview of what needs to be done:

Set up the server socket using socket(), bind(), listen(), fctnl();

• Your server must never block and the client can be bounced properly if necessary.
• It must be non-blocking and use only 1 poll() (or equivalent) for all the I/O
operations between the client and the server (listen included).
• poll() (or equivalent) must check read and write at the same time.
• You must never do a read or a write operation without going through poll() (or
equivalent).

I believe that based on the information we have so far, doing this is sufficient on the server side.

**Comment by vcwild** [comment]
Done!
