### ISSUE TITLE
Request Handling (Parsing the http request)

### ISSUE THREAD

**Issue by MatheusCervieri** [vcwild/webserv#5]
In a simple way the client send a request to the server and the server need to read this request and get the http information from it. 

Here we need to  implementing the logic for parsing and processing the incoming HTTP requests!

From what I understand, the server is waiting for a request from the client, when it receives the request, it receives a series of information in a string of characters.

It is necessary to take this information, parse it so that later we can send the response to the server based on the information that arrived.

We need to store this information in a data structure to compare with what's in our configuration file and send a response back to the client.

**Comment by vcwild** [comment]
parse types: GET POST DELETE

**Comment by iaurg** [comment]
Your server must be compatible with the web browser of your choice.

**Comment by vcwild** [comment]
Reopening this issue as I did not handle CHROME requests yet

**Comment by iaurg** [comment]
- [ ] Implement a way to log Requests
